name: rating_bar_updated
description: A customizable Rating Bar for flutter with half rating support
version: 0.2.0
homepage: https://github.com/pro-cms/rating_bar

environment:
  sdk: ">=2.12.0 <3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
